# Generated by Django 5.1.3 on 2024-11-18 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_alter_sprint_project'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sprint',
            name='name',
            field=models.CharField(max_length=200, unique=True),
        ),
        migrations.AlterField(
            model_name='task',
            name='name',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
